import psutil
import os
from datetime import datetime

def get_size(bytes, suffix="B"):
    """
    Scale bytes to its proper format
    e.g:
        1253656 => '1.20MB'
        1253656678 => '1.17GB'
    """
    factor = 1024
    for unit in ["", "K", "M", "G", "T", "P"]:
        if bytes < factor:
            return f"{bytes:.2f}{unit}{suffix}"
        bytes /= factor

def generate_report(output_path="metrics_report.md"):
    # CPU usage
    cpu_usage = psutil.cpu_percent(interval=1)
    
    # RAM usage
    svmem = psutil.virtual_memory()
    ram_total = get_size(svmem.total)
    ram_used = get_size(svmem.used)
    ram_percentage = svmem.percent
    
    # Disk I/O
    disk_io = psutil.disk_io_counters()
    disk_read = get_size(disk_io.read_bytes)
    disk_write = get_size(disk_io.write_bytes)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_content = f"""# Performance Metrics Report
Last Updated: {timestamp}

| Metric | Value |
| :--- | :--- |
| **CPU Usage** | {cpu_usage}% |
| **RAM Total** | {ram_total} |
| **RAM Used** | {ram_used} ({ram_percentage}%) |
| **Disk Read** | {disk_read} |
| **Disk Write** | {disk_write} |

---
*Note: This report is automatically generated by tracker.py.*
"""
    
    with open(output_path, "w") as f:
        f.write(report_content)
    
    print(f"Report generated successfully at {output_path}")

if __name__ == "__main__":
    generate_report()
